### ISSUE TITLE
Endpoint manquant : regions/{code}/communes

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/api-geo#100]
Présent dans la documentation mais non implémenté.

Peut être remplacé par https://geo.api.gouv.fr/communes?codeRegion=76 par exemple

**Comment by AntoineAugusti** [comment]
Duplicate of #94

**Comment by ThomasG77** [comment]
Nous avons aligné la documentation en enlevant sa description dans le end-point https://github.com/etalab/geo.api.gouv.fr/pull/86

Je met à jour la solution sur l'issue #94
