### ISSUE TITLE
Get old city in commune endpoint

### ISSUE THREAD

**Issue by VincentLanglet** [etalab/api-geo#105]
In the search query (cf https://geo.api.gouv.fr/adresse), there is `oldcity` value.

But when we're making a request on `/communes` endpoint (cf https://geo.api.gouv.fr/decoupage-administratif/communes), only actual city are reported.
When we're making a field for the city of the birth, we need old city too.

A flag in the query would be great.

**Comment by rhanka** [comment]
:+1: Old cities are really useful for birth places and should be searchable too.

Integration of @etalab/decoupage-administratif/data/historique-communes.json could be useful for that
