### ISSUE TITLE
Fuzzy search for communes

### ISSUE THREAD

**Issue by rhanka** [etalab/api-geo#116]
When doing quality rectification, fuzzy match based on city label (fuzzy) + dep code (strict) leads up to 98% of reidentification (with correct insee code) on birth places (base on real use case: french driving licence).

Same endpoint could still be used, with an option (like fuzzy=true or search=fuzzy) - using for example js-levenshtein library.

2 use cases : 
- when displaying some record to an enduser with "manual input historical data", UI suggest a rectification and an INSEE code for validation
- when doing bulk quality rectification, massive call to this API could be useful (in this case, csv enrichment like https://adresse.data.gouv.fr/csv would be very useful)

**Comment by jdesboeufs** [comment]
Sorry for the delay…
Fuzzy search is already available in the API Communes since 2016.
Juste read the doc :)
https://geo.api.gouv.fr/communes?nom=tou&boost=population
