### ISSUE TITLE
API Geo - MAJ 2021

### ISSUE THREAD

**Issue by ThomasG77** [etalab/api-geo#133]
Dépend de la mise à jour des données 2021 sur le dépôt https://github.com/etalab/decoupage-administratif et plus spécifiquement la branche cog2021 https://github.com/etalab/decoupage-administratif/tree/cog2021

Non publié à ce jour pour cause de problème pour reconstituer le graphe des évolutions des communes utilisé par nos outils pour retrouver depuis un ancien code postal ou insee la commune courante.
Deux options encore à trancher:

- attente selon résolution #134
- publication avec régression de la fonctionnalité historique

**Comment by ThomasG77** [comment]
PR pour ajouter les EPCI 2021 https://github.com/etalab/decoupage-administratif/pull/24

**Comment by agarrone** [comment]
Contexte : https://www.notion.so/apigouv/MAJ-Mill-sime-Octobre-2021-d33834c6a7c540d6bde7de1d8d37e820

**Comment by ThomasG77** [comment]
MAJ des données de population. Commit le plus notoire https://github.com/etalab/decoupage-administratif/commit/3b068542e01772bb715e417f4fd103e53a0564b3

**Comment by geoffreyaldebert** [comment]
- MaJ 2021 opérationnel sans l'historique mais non publié officiellement
- Besoin de vérifier si l'API est utilisé actuellement pour avoir des informations sur l'historique (via logs nginx)
