### ISSUE TITLE
Disparition de la ville principale pour les villes à arrondissement

### ISSUE THREAD

**Issue by raphaelbadia** [etalab/api-geo#151]
Bonjour,

depuis la MR #148 nous avons constaté la disparition des villes Paris, Marseille et Lyon : 
exemple : https://api-adresse.data.gouv.fr/search?limit=20&q=paris&type=municipality 

Auparavant nous avions en plus la ville de Paris dans les résultat sous le format 
```json
{
    "properties": {
        "label": "Paris",
         //        ............
        "type": "municipality",
        "name": "Paris",
        "postcode": "75001",
    }
}
``` 
Nous avions également Lyon (69001) et Marseille (13001).

Maintenant n'apparaissent plus que les arrondissements. Je ne suis pas certain : dois-je les ajouter manuellement de mon côté ou est-ce un bug ?

Merci d'avance,

**Comment by jdesboeufs** [comment]
Bonjour,

L'API Adresse que vous évoquez n'est pas optimisée pour la recherche de communes. C'est le rôle de l'API Géo, dont c'est pourtant le bon dépôt.

Néanmoins nous venons de corriger le problème, le déploiement en production sera effectif d'ici 22h00 heure de Paris.

**Comment by jdesboeufs** [comment]
C'est en production.
Merci pour le retour 💪🏻

**Comment by raphaelbadia** [comment]
merci !
