### ISSUE TITLE
Exposer la collectivité d'outre-mer

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/api-geo#154]
Bonjour,

Si les communes (ou assimilées) des collectivités d'outre-mer (COM) sont bien présentes dans l'API, leur COM de rattachement n'est pas accessible.
Il n'est d'ailleurs pas possible de lister les collectivités d'outre-mer comme on peut lister les départements ou les régions, alors même que le statut département-région de certains DROM est complexe.

Pourrait-on imaginer soit d'utiliser l'entrée `departement` soit créer un attribut `collectiviteOutremer` qui permette de récupérer le code et le nom ?

Exemple (Saint-Barthelemy) : https://geo.api.gouv.fr/communes/97701

En lien avec BaseAdresseNationale/ban-bal#2

**Comment by ThomasG77** [comment]
> Pourrait-on imaginer soit d'utiliser l'entrée departement soit créer un attribut collectiviteOutremer qui permette de récupérer le code et le nom ?

A l'amont de l'exposition d'une entrée, en reprenant la codification INSEE https://www.insee.fr/fr/information/2028040, il se pose le problème de la codification d'une hiérarchie à partir de code qui n'existe pas côté INSEE. Un récapitulatif ci-dessous

- [Saint-Pierre-et-Miquelon](https://www.insee.fr/fr/information/2028040#st-pierre-et-miquelon), code: absent (à priori, 975 utilisable mais non mentionné explicitement dans la doc) Code ISO 3166-1: SPM ou PM 
- [Saint-Barthélemy](https://www.insee.fr/fr/information/2028040#st-barthelemy), code: 97-7 (ou 97701 si code sur 5 caractères souhaité) Utiliser 977 pour coder sur 3 caractères? Code ISO 3166-1:  BLM ou BL
- [Saint-Martin](https://www.insee.fr/fr/information/2028040#st-martin), code: 97-8 (ou 97801 si code sur 5 caractères souhaité). Utiliser 978 pour coder sur 3 caractères? Code ISO 3166-1 : MAF ou MF
- [Terres australes et antarctiques françaises](https://www.insee.fr/fr/information/2028040#terres-australes): code absent (historiquement 98403) et maintenant code par "Districts administratifs". Encodé comme TF ou ATF (selon code ISO 3166-1 de https://fr.wikipedia.org/wiki/Terres_australes_et_antarctiques_fran%C3%A7aises)
- [Wallis et Futuna](https://www.insee.fr/fr/information/2028040#wallis-futuna), code: absent. Code ISO 3166-1  WLF ou WF
- [Polynésie française](https://www.insee.fr/fr/information/2028040#polynesie-francaise), code: absent (historiquement 98601 à 98606) Code ISO 3166-1: PYF ou PF 
- [Nouvelle-Calédonie](https://www.insee.fr/fr/information/2028040#nvelle-caledonie), code: absent (historiquement 98607) Code ISO 3166-1: NCL ou NC
- [Île de Clipperton](https://www.insee.fr/fr/information/2028040#clipperton), code: 98-9 (ou 98901 si code sur 5 caractères souhaité) Utiliser 989 pour coder sur 3 caractères? Sinon CP ou CPT mais https://fr.wikipedia.org/wiki/ISO_3166-1#Table_des_codes_exceptionnellement_r%C3%A9serv%C3%A9s_par_l%E2%80%99ISO_3166/MA https://www.iso.org/obp/ui/#iso:code:3166:CP

De ce fait, les codes à utiliser seraient ceux de l'ISO 3166-1, celui de Clipperton n'étant pas directement dans la base ISO 3166-1 directement mais dans ceux externes mais marqué à "Exceptionally reserved"

**Comment by ThomasG77** [comment]
Publié en prod

- https://geo.api.gouv.fr/communes/?nom=sigave&zone=metro,drom,com
- https://geo.api.gouv.fr/communes/?nom=sigave&zone=metro,drom,com&fields=nom,code,codeDepartement,codeRegion,codesPostaux,population,departement
- https://geo.api.gouv.fr/departements?zone=metro,drom,com
- https://geo.api.gouv.fr/regions?zone=metro,drom,com

Par ailleurs, la couche decoupage-administratif de https://openmaptiles.geo.data.gouv.fr a été mise à jour (communes, régions, départements)

**Comment by kvpt** [comment]
Bonjour,
@ThomasG77 Je ne sais pas si c'est lié a ce changement mais je constate un écart entre les données renvoyées par les points de terminaison communes et départements.
En effet si je requête l'api sans paramètre particulier, des communes COM me sont renvoyées, ce qui n'est pas le cas pour les départements. Ainsi la synchronisation des données de l'api dans ma base échoue car certains codes de département ne sont pas connus lors de l'insertion des villes.
En me basant sur l'exemple ci dessus, j'ai rajouter le paramètre zone=metro,drom,com qui corrige le problème.
Par contre il n'est pas mentionné dans la documentation de l'api disponible [ici](https://api.gouv.fr/documentation/api-geo).

**Comment by kvpt** [comment]
Au passage l'issue https://github.com/etalab/api-geo/issues/131 semble corrigée puisque ce problème c'est manifesté justement car ces communes sont désormais rattachées aux départements.

**Comment by ThomasG77** [comment]
> Par contre il n'est pas mentionné dans la documentation de l'api disponible [ici](https://api.gouv.fr/documentation/api-geo).

C'est dans mon "reste à faire"

**Comment by ThomasG77** [comment]
Fermé car maintenant référence à la clé `zone` dans la doc
