### ISSUE TITLE
Centre administratif des communes

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/api-geo#43]
Proposer le centre administratif des communes, en plus du centroïde.

**Comment by jdesboeufs** [comment]
@cquest On a une bonne couverture des mairies ou des centres-villes sur OSM ?

**Comment by cquest** [comment]
Tu as cette info dans feu le RGC, désormais remplacé par ADMIN EXPRESS... en L/O

http://professionnels.ign.fr/adminexpress

Il y a de quoi creuser avec cet ADMIN EXPRESS qui a l'air d'être mis à jour bien régulièrement...

**Comment by ThomasG77** [comment]
Implémenté via #160

Pour les communes morte pour la France, sans mairie, on prend le centre de la commune, n'ayant pas le choix si on veut toujours retourner l'information.

Les données ne sont pas encore au point sur les COM.

**A propos de la localisation des COM.**

Elle existe pour partie dans [service-public-fr](https://www.data.gouv.fr/fr/datasets/service-public-fr-annuaire-de-l-administration-base-de-donnees-locales/) où on retrouve des mairies de COM mais soit sans localisation soit avec localisation mais celle-ci ne semble pas toujours juste (cf https://lannuaire.service-public.fr/recherche?whoWhat=Mairie+%28collectivit%C3%A9+d%27outre-mer%29&where=).

Sinon, nous avons regardé du côté d'OpenStreetMap du tag `amenity=townhall` en filtrant sur les étendues des COM puis en vérifiant dans quelle commune exacte était l'élement (polygone ou point). Là, encore pas satisfaisant mais pour d'autres raisons: on a les mairies annexes donc des "doublons" sur une même commune. Dans certaines COM, l'entité administrative la plus petite n'est pas la commune mais le village/tribu donc ici encore plusieurs mairies pour un même code commune. Il i

Pour le moment, le choix est retomber sur le centre pour les COM quand on demande la mairie mais ce n'est pas satisfaisant sur le long terme et par ailleurs, on ne précise pas qu'on n'a pas réussi à obtenir la mairie et qu'on a pris le centre implicitement...
