### ISSUE TITLE
Route manquante : liste des communes par région

### ISSUE THREAD

**Issue by thibault** [etalab/api-geo#94]
Hello,

Sur la [doc technique concernant les communes](https://geo.api.gouv.fr/docs/communes), il est indiqué qu'il est possible d'obtenir la liste de toutes les communes par région.

    /regions/{code}/communes    Renvoi les communes d’une région

Or, sauf erreur de ma part, je ne trouve pas trace de cette route dans `server.js`. S'agit-il d'une url manquante ou d'une doc pas à jour ?

**Comment by ThomasG77** [comment]
La documentation n'était pas à jour. Nous avons supprimé la doc correspondante.

Au niveau fonctionnel, 2 choix pour pallier au besoin

- Pour filtrer par région lors de la recherche de commune, prendre une url du type https://geo.api.gouv.fr/communes?codeRegion=84&boost=population&nom=chamb
Utile principalement pour l'autocomplétion

- Pour récupérer toutes les communes de votre région, prendre https://geo.api.gouv.fr/communes?codeRegion=84&limit=10000 Si l'appel est répétitif, il peut être judicieux de stocker le résultat dans un fichier ou via un cache au niveau de l'infrastructure qui fait les appels plutôt qu'appeler l'API directement: cela consomme environ 480Ko pour l'exemple précédent. Si vous ajoutez les contours des communes, l'API peut remonter un fichier faisant 33Mo (https://geo.api.gouv.fr/communes?codeRegion=84&limit=5000&format=geojson&geometry=contour)
